#!/bin/bash
# =============================================================================
# gen-templates.sh — the template catalogue in docs/TEMPLATES.md
#
# Reads .templates/*/template.json and rewrites the part of docs/TEMPLATES.md
# between the two marker lines; the rest of the page is written by hand.
# Categories follow the dashboard's Templates page: the same aliases, the same
# order. Running it twice changes nothing.
#
#   docs/tools/gen-templates.sh           rewrite the catalogue
#   docs/tools/gen-templates.sh --check   exit 1 when the page is out of date
# =============================================================================
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
DOC="$ROOT/docs/TEMPLATES.md"
BEGIN='<!-- templates:begin (generated by docs/tools/gen-templates.sh, do not edit by hand) -->'
END='<!-- templates:end -->'

CHECK=false
case "${1:-}" in
    "") ;;
    --check) CHECK=true ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "usage: $0 [--check]" >&2; exit 2 ;;
esac

command -v jq >/dev/null 2>&1 || { echo "gen-templates: jq is required" >&2; exit 1; }
[[ -f "$DOC" ]] || { echo "gen-templates: $DOC is missing" >&2; exit 1; }
if ! grep -qxF "$BEGIN" "$DOC" || ! grep -qxF "$END" "$DOC"; then
    echo "gen-templates: $DOC lacks the marker lines:" >&2
    printf '  %s\n  %s\n' "$BEGIN" "$END" >&2
    exit 1
fi

shopt -s nullglob
files=("$ROOT"/.templates/*/template.json)
(( ${#files[@]} > 0 )) || { echo "gen-templates: no .templates/*/template.json found" >&2; exit 1; }

# The dashboard's categories (src/renderer/pages/Templates.tsx in the UI): id, label, the category
# strings each one takes in, and an emoji for the overview. Anything else lands in Other.
read -r -d '' FILTER <<'JQ' || true
def groups: [
  {id: "media",         label: "Media",         icon: "🎬", aliases: ["media", "photos", "content", "publishing"]},
  {id: "monitoring",    label: "Monitoring",    icon: "📈", aliases: ["monitoring", "metrics", "dashboard"]},
  {id: "web",           label: "Web",           icon: "🌐", aliases: ["web", "communication"]},
  {id: "databases",     label: "Databases",     icon: "🗄️", aliases: ["databases", "database", "db"]},
  {id: "development",   label: "Development",   icon: "🛠️", aliases: ["development", "dev"]},
  {id: "tools",         label: "Tools",         icon: "🧰", aliases: ["tools", "utilities", "remote"]},
  {id: "productivity",  label: "Productivity",  icon: "📝", aliases: ["productivity", "notes", "documents", "knowledge", "finance", "lifestyle"]},
  {id: "automation",    label: "Automation",    icon: "⚙️", aliases: ["automation", "notifications", "sync", "home", "smart-home"]},
  {id: "security",      label: "Security",      icon: "🛡️", aliases: ["security", "vpn", "privacy"]},
  {id: "network",       label: "Network",       icon: "🔌", aliases: ["network", "management"]},
  {id: "storage",       label: "Storage",       icon: "💾", aliases: ["storage", "backup"]},
  {id: "download",      label: "Download",      icon: "⬇️", aliases: ["download"]},
  {id: "entertainment", label: "Entertainment", icon: "🎮", aliases: ["entertainment", "ai", "gaming"]},
  {id: "other",         label: "Other",         icon: "📦", aliases: []}
];

# Markdown-safe text for a table cell
def cell: gsub("\\|"; "\\|") | gsub("\\*"; "\\*") | gsub("_"; "\\_") | gsub("<"; "&lt;");

# The first sentence of a description, cut at a colon or a dash when it runs long
def summary:
  (gsub("\\s+"; " ") | sub("^ "; "") | sub(" $"; "")) as $d
  | (($d | capture("^(?<s>.*?[.!?])(?= [A-Z0-9\"(]|$)").s) // $d) as $s
  | (if ($s | length) > 160 then
       ([($s | split(": ")[0]), ($s | split(" — ")[0])] | map(select(length >= 30 and length < ($s | length))) | min_by(length)) // $s
     else $s end)
  | sub("[.!?]$"; "");

# The port to open: the first *PORT* variable with a numeric default whose label names a web page,
# otherwise the first one with a numeric default
def mainport:
  [(.variables // [])[] | select((.name // "") | test("PORT")) | select((.default // "" | tostring) | test("^[0-9]+$"))] as $p
  | (($p | map(select((.label // "") | test("\\b(web|ui|dashboard|admin|console|editor|frontend|panel|client)\\b"; "i")))) + $p)[0].default
  // null;

def notes:
  [ (if .auth == "bypass" then "Own sign-in" else empty end),
    (if .singleton == true then "One per host" else empty end),
    (if ((.route_skip // []) | length) > 0 then "Not routed: " + ((.route_skip | map("`" + . + "`")) | join(", ")) else empty end),
    (if .route_override then "Routed as `" + (.route_override.subdomain // "?") + "` to port " + ((.route_override.port // "?") | tostring) else empty end),
    (if ((.optional_services // []) | length) > 0
       then "Optional: " + (((.optional_services | map(if type == "object" then .service else . end)) | map("`" + . + "`")) | join(", "))
       else empty end)
  ] | join(" · ");

def group_of: (.category // "" | ascii_downcase) as $c
  | ((groups | map(select(.aliases | index($c))) | .[0].id) // "other");

def slug: ascii_downcase | gsub(" "; "-");

# The overview names these first when a category has them (the rest follows alphabetically)
def featured: ["jellyfin", "plex", "immich", "sonarr", "grafana", "uptime-kuma", "prometheus", "netdata",
  "traefik", "nginx-proxy-manager", "wordpress", "ghost", "postgresql", "mariadb", "redis", "mongodb",
  "gitea", "code-server", "n8n", "it-tools", "stirling-pdf", "paperless-ngx", "mealie", "bookstack",
  "home-assistant", "node-red", "ntfy", "frigate", "vaultwarden", "authelia", "crowdsec", "wg-easy",
  "tailscale", "pihole", "adguard-home", "nextcloud", "syncthing", "minio", "qbittorrent", "sabnzbd",
  "minecraft", "ollama", "open-webui"];

def examples: (featured as $f | map(.name as $n | . + {rank: (($f | index($n)) // 1000)}) | sort_by(.rank, (.title | ascii_downcase)))[:4];

. as $all
| ($all | map(. + {group: group_of})) as $t
| [groups[] | . as $g | {g: $g, items: ($t | map(select(.group == $g.id)) | sort_by(.title | ascii_downcase))} | select(.items | length > 0)] as $cats
| [
    "**\($t | length) templates** in \($cats | length) categories, grouped the way the dashboard's Templates page groups them.",
    "",
    "| Category | Templates | For example |",
    "|---|---:|---|",
    ($cats[] | "| \(.g.icon) [\(.g.label)](#\(.g.label | slug)) | \(.items | length) | \([.items | examples | .[].title] | join(", ") | cell) |"),
    "",
    ($cats[] |
      "### \(.g.label)",
      "",
      "| Template | What it does | Port | Stack | Notes |",
      "|---|---|---|---|---|",
      (.items[] | "| \(.icon // "") **\(.title | cell)**<br>[`\(.name)`](../.templates/\(.name)) | \(.description | summary | cell) | \(mainport // "—") | `\(.target_stack // "—")` | \(notes) |"),
      "")
  ]
| .[]
JQ

tmp=$(mktemp)
trap 'rm -f "$tmp" "$tmp.cat"' EXIT
jq -rs "$FILTER" "${files[@]}" > "$tmp.cat"

# The page with the catalogue between the markers put in anew
awk -v begin="$BEGIN" -v end="$END" -v cat="$tmp.cat" '
    $0 == begin { print; while ((getline line < cat) > 0) print line; skip = 1; next }
    $0 == end   { skip = 0 }
    !skip       { print }
' "$DOC" > "$tmp"

if [[ "$CHECK" == true ]]; then
    if cmp -s "$tmp" "$DOC"; then
        echo "docs/TEMPLATES.md is up to date (${#files[@]} templates)"
        exit 0
    fi
    echo "docs/TEMPLATES.md is out of date: run docs/tools/gen-templates.sh" >&2
    exit 1
fi

if cmp -s "$tmp" "$DOC"; then
    echo "docs/TEMPLATES.md already up to date (${#files[@]} templates)"
else
    cat "$tmp" > "$DOC"
    echo "docs/TEMPLATES.md written (${#files[@]} templates)"
fi
